<?php
$contest = $this->getContest();
if (is_string($contest)) : ?>
    <h1><?php echo $contest; ?></h1>
<?php else : ?>
    <h1><?php echo $contest->getTitle(); ?></h1>
    <h3><?php echo $this->__('Add Contestant')?></h3>
    <form action="<?php echo $this->getActionUrl() ?>" method="post" id="form-validate">
        <div class="contestant-field-wrap">
            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey()?>" />

            <label for="contestantFirstname" class="required"><?php echo $this->__('First name'); ?></label>
            <div class="input-box">
                <input type="text" id="contestantFirstname" name="contestant-firstname" class="input-text required-entry" title="<?php
                echo $this->__('First name'); ?>">
            </div>
            <br />

            <label for="contestantLastname" class="required"><?php echo $this->__('Last name'); ?></label>
            <div class="input-box">
                <input type="text" id="contestantLastname" name="contestant-lastname" class="input-text required-entry" title="<?php
                echo $this->__('Last name'); ?>">
            </div>
            <br />

            <label for="contestantDob" class="required"><?php echo $this->__('Date of birth'); ?></label>
            <div class="input-box">
                <input type="date" id="contestantDob" name="contestant-dob" class="input-text required-entry" title="<?php echo
                $this->__('Date of birth'); ?>">
            </div>
            <br />

            <label for="contestantCountry" class="required"><?php echo $this->__('Country'); ?></label>
            <div class="input-box">
                <?php
                $countries = Mage::getResourceModel('directory/country_collection')->loadData()->toOptionArray(false);
                if (count($countries) > 0) :?>
                    <select id="contestantCountry" name="contestant-country" class="required-entry" title="<?php echo $this->__('Country'); ?>">
                        <option value=""><?php echo $this->__('Select Country'); ?></option>
                        <?php foreach($countries as $country) : ?>
                            <option value="<?php echo $country['value']?>"><?php echo $country['label']?></option>
                        <?php endforeach; ?>
                    </select>
                <?php endif; ?>
            </div>
            <br />

            <label for="contestantCity" class="required"><?php echo $this->__('City'); ?></label>
            <div class="input-box">
                <input type="text" id="contestantCity" name="contestant-city" class="input-text required-entry" title="<?php echo
                $this->__('City'); ?>">
            </div>
            <br />

            <label for="contestantEmail"><?php echo $this->__('Email'); ?></label>
            <div class="input-box">
                <input type="email" id="contestantEmail" name="contestant-email" class="input-text validate-email" title="<?php echo
                $this->__('Email'); ?>">
            </div>
            <br />

            <label for="contestantMessage" class="required"><?php echo $this->__('Message'); ?></label>
            <div class="input-box">
                <textarea id="contestantMessage" name="contestant-message" class="input-text required-entry" title="<?php echo
                $this->__('Message'); ?>"></textarea>
            </div>
            <br />

            <div class="input-box">
                <input type="hidden" id="contestantContestId" name="contestant-contest-id" value="<?php echo
                $contest->getId(); ?>" readonly>
            </div>

            <button type="submit" id="addContestantButton" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
    </form>
    <script>
        // < ![CDATA[
            var addContestant = new VarienForm('form-validate');
        // ]]>
    </script>
<?php endif; ?>